# Generated by Django 4.2.3 on 2023-07-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Name', models.CharField(default='Nil', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Cost', models.IntegerField(blank=True, default='0', null=True)),
                ('Quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('Quantity_sold', models.IntegerField(blank=True, default='0', null=True)),
                ('Selling_price', models.IntegerField(blank=True, default='0', null=True)),
                ('Profit_earned', models.IntegerField(blank=True, default='0', null=True)),
                ('Revenue', models.IntegerField(default='0', null=True)),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
    ]
